const questions = [
  {
    question: "Яка мова працює у браузері?",
    answers: ["Java", "C", "Python", "JavaScript"],
    correct: 4,
    score: "$100",
  },
  {
    question: "Що означає CSS?",
    answers: [
      "Central Style Sheets",
      "Cascading Style Sheets",
      "Cascading Simple Sheets",
      "Cars SUVs Sailboats",
    ],
    correct: 2,
    score: "$200",
  },
  {
    question: "Що означає HTML?",
    answers: [
      "Hypertext Markup Language",
      "Hypertext Markdown Language",
      "Hyperloop Machine Language",
      "Helicopters Terminals Motorboats Lamborginis",
    ],
    correct: 1,
    score: "$300",
  },
  {
    question: "У якому році було створено JavaScript?",
    answers: ["1996", "1995", "1994", "всі відповіді невірні"],
    correct: 2,
    score: "$500",
  },
  {
    question: "Якої події не існує для addEventListener?",
    answers: ["click", "submit", "enter", "focus"],
    correct: 3,
    score: "$1000",
  },
  {
    question: "Що означає CSS?",
    answers: [
      "Central Style Sheets",
      "Cascading Style Sheets",
      "Cascading Simple Sheets",
      "Cars SUVs Sailboats",
    ],
    correct: 2,
    score: "$2000",
  },
  {
    question: "Що означає HTML?",
    answers: [
      "Hypertext Markup Language",
      "Hypertext Markdown Language",
      "Hyperloop Machine Language",
      "Helicopters Terminals Motorboats Lamborginis",
    ],
    correct: 1,
    score: "$4000",
  },
  {
    question: "У якому році було створено JavaScript?",
    answers: ["1996", "1995", "1994", "всі відповіді невірні"],
    correct: 2,
    score: "$8000",
  },
  {
    question: "Яка мова працює у браузері?",
    answers: ["Java", "C", "Python", "JavaScript"],
    correct: 4,
    score: "$16000",
  },
  {
    question: "Що означає CSS?",
    answers: [
      "Central Style Sheets",
      "Cascading Style Sheets",
      "Cascading Simple Sheets",
      "Cars SUVs Sailboats",
    ],
    correct: 2,
    score: "$32000",
  },
  {
    question: "Якої події не існує для addEventListener?",
    answers: ["click", "submit", "enter", "focus"],
    correct: 3,
    score: "$64000",
  },
  {
    question: "У якому році було створено JavaScript?",
    answers: ["1996", "1995", "1994", "всі відповіді невірні"],
    correct: 2,
    score: "$125000",
  },
  {
    question: "Що означає CSS?",
    answers: [
      "Central Style Sheets",
      "Cascading Style Sheets",
      "Cascading Simple Sheets",
      "Cars SUVs Sailboats",
    ],
    correct: 2,
    score: "$250000",
  },
  {
    question: "Що означає HTML?",
    answers: [
      "Hypertext Markup Language",
      "Hypertext Markdown Language",
      "Hyperloop Machine Language",
      "Helicopters Terminals Motorboats Lamborginis",
    ],
    correct: 1,
    score: "$500000",
  },
  {
    question: "Якої події не існує для addEventListener?",
    answers: ["click", "submit", "enter", "focus"],
    correct: 3,
    score: "$1000000",
  },
];
